### ISSUE TITLE
Creating a user query to query on daterange and keyword

### ISSUE THREAD

**Issue by ennsk** [Clarivate-SAR/woslite_py_client#1]
Hey there,

I'm trying to query the WOS lite API on a keyword and date range.  From the 'query examples', I can only find how to search on the key word ( **usr_query = 'TS=(' + keyword + ')'** ) but I don't see any extra documentation on how to query using other parameters.  Is there documentation anywhere on this?

My code to query on a keyword
```
import woslite_client
from woslite_client.rest import ApiException

wos_apikey = config['wos_apikey']
configuration = woslite_client.Configuration()
configuration.api_key['X-ApiKey'] = wos_apikey

res = search_api_instance.root_get(database_id, usr_qkeyword = '"Brachylagus idahoensis"'
database_id = 'WOS'
usr_query = 'TS=(' + keyword + ')'
count = 100
first_record = 1
lang = 'en'
sort_field = 'PY+D'uery, count, first_record, lang=lang,
                                                                 sort_field=sort_field)
```

Thanks,
Kyle

**Comment by maloku** [comment]
Hi Kyle,

What kind of date do you need? Do you mean the published year?

The Query language does not support > or < operators but you can use boolean operators to include multiple values,e.g.

TS=(keyword1 or keyword2) and PY=(2020 or 2021)
You can find more information at
http://images.webofknowledge.com//WOKRS529AR7/help/WOS/hp_advanced_examples.html

Thanks,
Kadri

**Comment by ennsk** [comment]
This is perfect!

Thanks Kadri,
Kyle


--

Kyle Enns

Developer /  Operations Research Analyst

(970) 226-9201

Fort Collins Science Center

2150 Centre Ave, Bldg C

Fort Collins, CO 80526

________________________________
