### ISSUE TITLE
ERROR: Command errored out with exit status 128: git clone -q https://github.com/Clarivate-SAR/woslite-py-client.git

### ISSUE THREAD

**Issue by manentai** [Clarivate-SAR/woslite_py_client#2]
Any idea why I am getting this error?

    pip install git+https://github.com/Clarivate-SAR/woslite-py-client.git

    Collecting git+https://github.com/Clarivate-SAR/woslite-py-client.git
    Cloning https://github.com/Clarivate-SAR/woslite-py-client.git to /private/var/folders/3g/85zrjvfs1rs426yfhnn7f35r0000gn/T/pip-req-build-iphdfnef
    ERROR: Command errored out with exit status 128: git clone -q https://github.com/Clarivate-SAR/woslite-py-client.git /private/var/folders/3g/85zrjvfs1rs426yfhnn7f35r0000gn/T/pip-req-build-iphdfnef Check the logs for full command output.

I actually have a subscription through my university and also got an API key from Clarivate support.

**Comment by manentai** [comment]
I have cloned the repo with Github desktop and it worked.

**Comment by maloku** [comment]
I could not reproduce it in my environment. Seems like some git configuration issues. https://stackoverflow.com/questions/58424348/pip-cannot-clone-from-https-anymore-error-128

Anyhow, thanks for posting the workaround. 

At some point, we will publish this package, maybe it will be easier to import then.
