### ISSUE TITLE
how to retrieve more that the first 100 records

### ISSUE THREAD

**Issue by manentai** [Clarivate-SAR/woslite_py_client#3]
from the documentation, I am not able to understand how to get the full list of records:

    try:
        # Find record(s) by user query
        api_response = search_api_instance.root_get(database_id, usr_query, 100, 1, lang=lang, sort_field=sort_field)
    except ApiException as e:
        print("Exception when calling SearchApi->root_get: {}".format(e))

I can see that api_response.query_result is:

    {'query_id': 4, 'records_found': 823, 'records_searched': 67044985}

But in api_response.data I only have the first 100 (which I understand is the max limit for the "pagination")... how to proceed and use query_id to get the remaining records?

**Comment by maloku** [comment]
You can use query_id in the loop. The following snippet will iterate (incrementing by 100) records until records_found is reached. 

    for i in range(101, api_response.query_result.records_found, 100):
        api_response = search_api_instance.query_query_id_get(api_response.query_result.query_id, 100, i)
        print(api_response)

**Comment by manentai** [comment]
thank you for your help, but this loop fails at the second iteration with:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-21-1f5427be001d> in <module>
     17         for i in range(101, api_response.query_result.records_found, 100):
     18             print("dentro")
    ---> 19             api_response = search_api_instance.query_query_id_get(api_response.query_result.query_id, 100, i)
     20             for i in api_response.data:
     21                 results.append(i)

    AttributeError: 'NoneType' object has no attribute 'query_id'

looks like at the second iteration of the `for` loop, `api_response.query_result` is `None`

**Comment by manentai** [comment]
thank you for your help, but it looks like at the second iteration within the loop you suggested, `api_response.query_result` is `None`:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-24-306632051575> in <module>
         17         for dd in range(101, api_response.query_result.records_found, 100):
         18             print("debug")
    ---> 19             api_response = search_api_instance.query_query_id_get(api_response.query_result.query_id, 100, dd)
         20             for x in api_response.data:
         21                 results.append(x)

    AttributeError: 'NoneType' object has no attribute 'query_id'

**Comment by manentai** [comment]
@maloku do you happen to have any suggestion on why `api_response.query_result` is None? am I missing something?

**Comment by gneissone** [comment]
@manentai The issue is that the WoS API doesn't return the query ID in the subsequent responses since you are supplying it as part of the request itself. The trick is to save the query_id after you receive the initial results, then use that same query_id to make all subsequent requests as you loop through the records.

```
try:
    api_response = search_api_instance.root_get(database_id, usr_query, count, first_record, lang=lang,
                                                         sort_field=sort_field)
    print(api_response)
    query_id = api_response.query_result.query_id
    for i in range(101, api_response.query_result.records_found, 100):
        api_response = search_api_instance.query_query_id_get(query_id, 100, i)
        print(api_response)

except ApiException as e:
    print("Exception when calling SearchApi->root_get: {}".format(e))
```

**Comment by manentai** [comment]
just for the future reader, I had to add a `time.sleep(3)` within the loop in order not to receive a `Too many requests` error.

**Comment by maloku** [comment]
Thanks @gneissone - I missed that query id should be declared before the loop, exactly for the reason you mentioned.

@manentai I am wondering why you have to wait 3 seconds. Have you tried to wait for 1 sec?

**Comment by manentai** [comment]
no specific reasons, but if you don't wait for at least some time, it will bounce back with the `too many requests` error. I used 3 because it sounded enough time to me, will try also 1 in the future...
