### ISSUE TITLE
how to get X-ApiKey?

### ISSUE THREAD

**Issue by kongdd** [Clarivate-SAR/woslite_py_client#4]

**Comment by maloku** [comment]
Hi @kongdd,

You need to create or (use your Clarivate account that you use to access other products) in https://developer.clarivate.com. 
Once you have an account you can follow the steps described
![image](https://user-images.githubusercontent.com/535127/119683774-37506000-be44-11eb-885d-d6434f2cf551.png)

Please contact your University Library or Clarivate Support to ensure that you can get access to the API - Web of Science subscribers can have access to this API.
